Repository NOAA-EMC/EVS, pull requests merged in 2024-11, with the labels that each got.

#603 Mesoscale NAM/RAP Fixes and Additions - no restart
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_precip_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_precip_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.ecf
  jobs/JEVS_MESOSCALE_PLOTS
  jobs/JEVS_MESOSCALE_STATS
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.nam
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.rap
  parm/metplus_config/stats/mesoscale/grid2obs/PB2NC_obsMETAR.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PB2NC_obsRAOB.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR_PTYPE.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR_VAR2.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsNDAS_PrepBufr.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsRAOB.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsRAOB_VAR2.conf
  parm/metplus_config/stats/mesoscale/grid2obs/RegridDataPlane_fcstMESOSCALE_PTYPE.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_GatherByCycle.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_GatherByDay.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_obsMETAR_GatherByDay.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_obsNDAS_GatherByDay.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_obsRAOB_GatherByDay.conf
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/stats/mesoscale/exevs_mesoscale_nam_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_nam_precip_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_nam_snowfall_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_precip_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_snowfall_stats.sh
  ush/mesoscale/mesoscale_check_input_data.py
  ush/mesoscale/mesoscale_check_settings.py
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_stats_grid2obs_preprocess_prepbufr.py
  ush/mesoscale/mesoscale_stats_grid2obs_var_defs.py
  ush/mesoscale/mesoscale_util.py
  ush/mesoscale/prune_stat_files.py
Labels: enhancement

#608 Fixing bug in the ceiling processing for the analysis perfdiag
  ush/analyses/performance_diagram.py
Labels: enhancement

#607 Feature/sref fixes
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cape_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cloud_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cnv_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_spatial_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_td2m_last90days_plots.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_precip_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cape_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cloud_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cnv_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_spatial_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_td2m_last90days_plots.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_sref_grid2obs_stats.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_sref_precip_stats.ecf
  parm/metplus_config/stats/mesoscale/grid2obs/EnsembleStat_fcstSREF_obsPREPBUFR.conf
  parm/metplus_config/stats/mesoscale/grid2obs/GenEnsProd_fcstSREF_obsPREPBUFR.conf
  parm/metplus_config/stats/mesoscale/grid2obs/Pb2nc_obsGFS_Prepbufr.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstSREF_obsPREPBUFR_cnv.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstSREF_obsPREPBUFR_mean.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstSREF_obsPREPBUFR_prob.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnlysis_fcstSREF_obsPREPBUFR_GatherByDay.conf
  parm/metplus_config/stats/mesoscale/precip/EnsembleStat_fcstSREF_obsCCPA_G212.conf
  parm/metplus_config/stats/mesoscale/precip/GenEnsProd_fcstSREF_obsCCPA_G212.conf
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstSREF_obsCCPA_mean_G212.conf
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstSREF_obsCCPA_mean_G240.conf
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstSREF_obsCCPA_prob_G212.conf
  parm/metplus_config/stats/mesoscale/precip/PcpCombine_fcstSREF_APCP06h.conf
  parm/metplus_config/stats/mesoscale/precip/PcpCombine_fcstSREF_APCP24h.conf
  parm/metplus_config/stats/mesoscale/precip/StatAnlysis_fcstSREF_obsCCPA_GatherByDay.conf
  scripts/plots/mesoscale/exevs_mesoscale_sref_cape_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cloud_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cnv_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_precip_spatial_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_td2m_plots.sh
  scripts/stats/mesoscale/exevs_mesoscale_sref_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_sref_precip_stats.sh
  ush/mesoscale/evs_prepare_sref.sh
  ush/mesoscale/evs_sref_average_cnv.sh
  ush/mesoscale/evs_sref_cnv.sh
  ush/mesoscale/evs_sref_gather.sh
  ush/mesoscale/evs_sref_grid2obs.sh
  ush/mesoscale/evs_sref_precip.sh
  ush/mesoscale/ush_sref_plot_cnv_py/prune_stat_files.py
  ush/mesoscale/ush_sref_plot_precip_py/prune_stat_files.py
  ush/mesoscale/ush_sref_plot_precip_py/sref_atmos_util.py
  ush/mesoscale/ush_sref_plot_py/prune_stat_files.py
Labels: enhancement, NCO Bugzilla

#609 feature/EVS-NWPS_regions
  dev/drivers/scripts/plots/nwps/jevs_nwps_wave_grid2obs_plots.sh
  dev/drivers/scripts/stats/nwps/jevs_nwps_wave_grid2obs_stats.sh
  jobs/JEVS_NWPS_PLOTS
  jobs/JEVS_NWPS_STATS
  parm/metplus_config/plots/nwps/wave_grid2obs/py_plotting_wave.config
  parm/metplus_config/stats/nwps/wave_grid2obs/PointStat_fcstNWPS_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/StatAnalysis_fcstNWPS_obsNDBC.conf
  scripts/plots/nwps/exevs_nwps_wave_grid2obs_plots.sh
  scripts/prep/nwps/exevs_nwps_wave_grid2obs_prep.sh
  scripts/stats/nwps/exevs_nwps_wave_grid2obs_stats.sh
  ush/nwps/evs_wave_leadaverages.sh
  ush/nwps/evs_wave_timeseries.sh
  ush/nwps/lead_average.py
  ush/nwps/time_series.py
Labels: enhancement

#611 Feature/subseasonal mpmd plots fix
  scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh
  scripts/plots/subseasonal/exevs_subseasonal_grid2obs_plots.sh
  ush/subseasonal/create_METplus_subseasonal_output_dirs.py
  ush/subseasonal/subseasonal_copy_job_dir_output.py
  ush/subseasonal/subseasonal_plots.py
  ush/subseasonal/subseasonal_plots_grid2grid_create_job_scripts.py
  ush/subseasonal/subseasonal_plots_grid2obs_create_job_scripts.py
  ush/subseasonal/subseasonal_plots_lead_average.py
  ush/subseasonal/subseasonal_plots_performance_diagram.py
  ush/subseasonal/subseasonal_plots_time_series.py
Labels: NCO Bugzilla
