Repository NOAA-EMC/EVS, pull requests merged in 2024-09, with the labels that each got.

#546 feature/update_beta5
  versions/run.ver
Labels: update

#547 feature/update_rtofs_ver
  versions/run.ver
Labels: update

#549 bugfix/subseasonal_avg_check
  ush/subseasonal/subseasonal_util.py
Labels: bug

#563 Bugfix/correct subseasonal OSI and GHRSST averaging
  dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
  ush/subseasonal/subseasonal_util.py
Labels: bug

#566 feature/EVSv2-RTOFS_additions1
  jobs/JEVS_RTOFS_PREP
  parm/metplus_config/prep/rtofs/grid2obs/ASCII2NC_obsARGO.conf
  parm/metplus_config/prep/rtofs/grid2obs/ASCII2NC_obsNDBC.conf
  scripts/prep/rtofs/exevs_rtofs_prep.sh
  ush/rtofs/rtofs_prep_regions.sh
  ush/rtofs/rtofs_prep_trim_ndbc_files.py
Labels: enhancement

#565 Adjust columns lists used for METv12.0 stats
  ush/cam/plot_util.py
Labels: update

#569 feature/EVS-GLWU_LC_buoy
  ush/glwu/glwu_wave_prep_read_ndbc.py
Labels: enhancement
