Repository NOAA-EMC/EVS, pull requests merged in 2024-12, with the labels that each got.

#613 Bugfix/rrfs fixes 1
  dev/drivers/scripts/plots/cam/jevs_cam_radar_nbrcnt_plots_last31days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_radar_nbrcnt_plots_last90days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_radar_nbrctc_plots_last31days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_radar_nbrctc_plots_last90days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_severe_nbrcnt_plots_last31days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_severe_nbrcnt_plots_last90days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_severe_nbrctc_plots_last31days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_severe_nbrctc_plots_last90days.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_grid2obs_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_radar_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_severe_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_snowfall_stats.sh
  ecf/scripts/plots/cam/jevs_cam_radar_nbrcnt_plots_last31days.ecf
  ecf/scripts/plots/cam/jevs_cam_radar_nbrcnt_plots_last90days.ecf
  ecf/scripts/plots/cam/jevs_cam_radar_nbrctc_plots_last31days.ecf
  ecf/scripts/plots/cam/jevs_cam_radar_nbrctc_plots_last90days.ecf
  ecf/scripts/plots/cam/jevs_cam_severe_nbrcnt_plots_last31days.ecf
  ecf/scripts/plots/cam/jevs_cam_severe_nbrcnt_plots_last90days.ecf
  ecf/scripts/plots/cam/jevs_cam_severe_nbrctc_plots_last31days.ecf
  ecf/scripts/plots/cam/jevs_cam_severe_nbrctc_plots_last90days.ecf
  ecf/scripts/prep/cam/jevs_cam_rrfs_precip_prep_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_grid2obs_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_radar_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_severe_stats.ecf
  parm/evs_config/cam/config.evs.prod.prep.cam.atmos.precip.rrfs
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.grid2obs.rrfs
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.rrfs
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.rrfs
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_FIREWX.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_FIREWX_VAR2.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_VAR2.conf
  scripts/plots/cam/exevs_cam_firewxnest_grid2obs_plots.sh
  scripts/prep/cam/exevs_rrfs_precip_prep.sh
  scripts/prep/cam/exevs_rrfs_severe_prep.sh
  scripts/stats/cam/exevs_cam_rrfs_firewxnest_grid2obs_stats.sh
  scripts/stats/cam/exevs_rrfs_grid2obs_stats.sh
  scripts/stats/cam/exevs_rrfs_precip_stats.sh
  scripts/stats/cam/exevs_rrfs_radar_stats.sh
  scripts/stats/cam/exevs_rrfs_snowfall_stats.sh
  ush/cam/cam_check_input_data.py
  ush/cam/cam_plots_precip_last90days_graphx_defs.py
  ush/cam/cam_plots_snowfall_graphx_defs.py
  ush/cam/cam_stats_grid2obs_var_defs.py
Labels: enhancement

#605 ops changes for post WCOSS changes
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.sh
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.ecf
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.ecf
  ecf/scripts/plots/cam/jevs_cam_precip_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.ecf
  scripts/plots/cam/exevs_cam_precip_plots.sh
  scripts/plots/cam/exevs_href_grid2obs_ecnt_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_separate_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
Labels: update

#606 dev changes for post WCOSS changes
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_precip_plots_last31days.sh
  dev/drivers/scripts/plots/cam/jevs_cam_precip_plots_last90days.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past90days_plots.sh
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.ecf
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.ecf
  ecf/scripts/plots/cam/jevs_cam_precip_plots_last31days.ecf
  ecf/scripts/plots/cam/jevs_cam_precip_plots_last90days.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past90days_plots.ecf
  scripts/plots/cam/exevs_cam_precip_plots.sh
  scripts/plots/cam/exevs_href_grid2obs_ecnt_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_separate_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_profile3_plots.sh
Labels: update

#617 ops_wcoss2_update_part2
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past90days_plots.sh
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past90days_plots.ecf
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_profile3_plots.sh
  versions/run.ver
Labels: bug

#615 Bugfix/cam fixes 4
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_FIREWX.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_FIREWX_VAR2.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_VAR2.conf
  ush/cam/cam_create_output_dirs.py
  ush/cam/cam_stats_grid2obs_create_job_script.py
  ush/cam/cam_stats_precip_create_job_script.py
  ush/cam/cam_stats_snowfall_create_job_script.py
  ush/cam/cam_util.py
  ush/cam/lead_average.py
Labels: bug, enhancement

#618 Bugfix/cam fixes 5
  dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hrrr_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_namnest_severe_prep.sh
  dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
  ecf/scripts/prep/cam/jevs_cam_hrrr_severe_prep_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_namnest_precip_stats_vhr_master.ecf
  ush/cam/cam_plots_precip_spatial_map.py
  ush/cam/cam_stats_precip_create_job_script.py
  ush/cam/cam_stats_snowfall_create_job_script.py
  ush/cam/df_preprocessing.py
Labels: bug

#616 replaced mallory.row in MAILTO with qi.shi for global-det
  dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh
  dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cmc_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cmc_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cmc_regional_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_dwd_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_wmo_daily_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_wmo_monthly_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_imd_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_imd_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_jma_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_jma_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_metfra_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ukmet_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ukmet_atmos_grid2obs_stats.sh
Labels: cleanup

#619 Feature/mesoscale mpmd fix
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.ecf
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.grid2obs
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.headline
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.precip
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.snowfall
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR_PTYPE.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsMETAR_VAR2.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsNDAS_PrepBufr.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsRAOB.conf
  parm/metplus_config/stats/mesoscale/grid2obs/PointStat_fcstMESOSCALE_obsRAOB_VAR2.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_GatherByCycle.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_obsMETAR_GatherByDay.conf
  parm/metplus_config/stats/mesoscale/grid2obs/StatAnalysis_fcstMESOSCALE_obsRAOB_GatherByDay.conf
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_headline_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_snowfall_plots.sh
  scripts/stats/mesoscale/exevs_mesoscale_nam_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_grid2obs_stats.sh
  ush/mesoscale/mesoscale_create_child_workdirs.py
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_plots_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_plots_headline_create_job_script.py
  ush/mesoscale/mesoscale_plots_precip_create_job_script.py
  ush/mesoscale/mesoscale_plots_snowfall_create_job_script.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_merged_ptype.py
Labels: NCO Bugzilla

#604 global_ens: add restart capability to atmos grid2grid and precip stats jobs
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_precip_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2grid_stats.sh
  ecf/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_precip_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_precip_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_precip_stats.ecf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/StatAnlysis_fcstGENS_obsAnalysis_GatherByDay.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/StatAnlysis_fcstGENS_obsCCPA_GatherByDay.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/StatAnlysis_fcstGENS_obsGHRSST_GatherByDay.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/StatAnlysis_fcstGENS_obsNOHRSC_GatherByDay.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/StatAnlysis_fcstGENS_obsOSI_SAF_GatherByDay.conf
  sorc/evs_g2g_adjustCMC.fd/evs_g2g_adjustCMC.f
  ush/global_ens/evs_global_ens_atmos_grid2grid.sh
Labels: NCO Bugzilla

#622 bugfix/ops_cam_href_spcoutlook
  ush/cam/evs_href_gather.sh
Labels: bug

#623 bugfix/dev_cam_href_spcoutlook
  ush/cam/evs_href_gather.sh
Labels: bug

#624 bugfix/ops_jevs_mesoscale_sref_cape_past90days_plots
  ush/mesoscale/ush_sref_plot_py/lead_average.py
  versions/run.ver
Labels: bug
