Repository NOAA-EMC/EVS, pull requests merged in 2024-10, with the labels that each got.

#570 feature/update_obsproc_v1.3
  dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.sh
  dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.sh
  ecf/scripts/stats/cam/jevs_cam_href_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.ecf
  ecf/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.ecf
  ush/global_det/lead_average.py
  ush/global_det/time_series.py
Labels: update

#572 feature/subseasonal_plot_unit_fixes
  jobs/JEVS_SUBSEASONAL_PLOTS
  ush/subseasonal/subseasonal_util.py
Labels: bug

#571 Feature/mesoscale beta5
  ush/mesoscale/mesoscale_stats_grid2obs_var_defs.py
  ush/mesoscale/plot_util.py
  ush/mesoscale/settings.py
Labels: update

#577 bugfix/subseasonal_plot_unit_fix_prod
  ush/subseasonal/subseasonal_util.py
Labels: bug

#579 Fix unit conversion logic
  ush/analyses/plot_util.py
  ush/aqm/plot_util.py
  ush/cam/plot_util.py
  ush/global_ens/ush_gens_plot_py/plot_util.py
  ush/mesoscale/plot_util.py
Labels: bug

#580 feature/EVSv2-nfcens_png_names
  parm/metplus_config/plots/nfcens/wave_grid2obs/py_plotting_wave.config
  scripts/plots/nfcens/exevs_nfcens_wave_grid2obs_plots.sh
  ush/nfcens/lead_average.py
  ush/nfcens/plot_util.py
  ush/nfcens/time_series.py
Labels: enhancement

#576 Update for WAFSv7.0 implementation
  jobs/JEVS_WAFS_ATMOS_STATS
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGCIP.conf
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGFS.conf
  ush/wafs/evs_wafs_atmos_stats_preparedata.sh
Labels: update

#578 feature/global_det_beta5
  ush/global_det/global_det_atmos_util.py
  ush/global_det/plot_util.py
  ush/global_det/settings.py
Labels: update

#581 bugfix/global_det_units
  ush/global_det/global_det_atmos_plots_specs.py
  ush/global_det/global_det_atmos_plots_threshold_average.py
  ush/global_det/global_det_atmos_plots_time_series.py
  ush/global_det/global_det_atmos_util.py
Labels: bug

#584 Feature/evs nwps initialized
  dev/drivers/scripts/plots/nwps/README.md
  dev/drivers/scripts/plots/nwps/jevs_nwps_wave_grid2obs_plots.sh
  dev/drivers/scripts/prep/nwps/README.md
  dev/drivers/scripts/prep/nwps/jevs_nwps_wave_grid2obs_prep.sh
  dev/drivers/scripts/stats/nwps/README.md
  dev/drivers/scripts/stats/nwps/jevs_nwps_wave_grid2obs_stats.sh
  dev/modulefiles/nwps/nwps_plots.sh
  dev/modulefiles/nwps/nwps_prep.sh
  dev/modulefiles/nwps/nwps_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/nwps/jevs_nwps_wave_grid2obs_plots.ecf
  ecf/scripts/prep/nwps/jevs_nwps_wave_grid2obs_prep.ecf
  ecf/scripts/stats/nwps/jevs_nwps_wave_grid2obs_stats.ecf
  jobs/JEVS_NWPS_PLOTS
  jobs/JEVS_NWPS_PREP
  jobs/JEVS_NWPS_STATS
  parm/metplus_config/plots/nwps/grid2grid/README.md
  parm/metplus_config/plots/nwps/grid2obs/README.md
  parm/metplus_config/plots/nwps/wave_grid2obs/py_plotting_wave.config
  parm/metplus_config/prep/nwps/wave_grid2obs/ASCII2NC_obsNDBC.conf
  parm/metplus_config/prep/nwps/wave_grid2obs/PB2NC_wave.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/PointStat_fcstNWPS_obsGDAS_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/PointStat_fcstNWPS_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/StatAnalysis_fcstNWPS_obsGDAS.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/StatAnalysis_fcstNWPS_obsNDBC.conf
  scripts/plots/nwps/README.md
  scripts/plots/nwps/exevs_nwps_wave_grid2obs_plots.sh
  scripts/prep/nwps/README.md
  scripts/prep/nwps/exevs_nwps_wave_grid2obs_prep.sh
  scripts/stats/nwps/README.md
  scripts/stats/nwps/exevs_nwps_wave_grid2obs_stats.sh
  ush/nwps/README.md
  ush/nwps/check_variables.py
  ush/nwps/df_preprocessing.py
  ush/nwps/evs_wave_leadaverages.sh
  ush/nwps/evs_wave_timeseries.sh
  ush/nwps/lead_average.py
  ush/nwps/nwps_wave_prep_read_ndbc.py
  ush/nwps/plot_util.py
  ush/nwps/plotter.py
  ush/nwps/prune_stat_files.py
  ush/nwps/settings.py
  ush/nwps/string_template_substitution.py
  ush/nwps/time_series.py
  ush/nwps/time_util.py
Labels: enhancement

#587 feature/global_det_cape_config
  ush/global_det/global_det_atmos_plots_grid2obs_create_job_scripts.py
  ush/global_det/global_det_atmos_stats_grid2obs_create_job_scripts.py
Labels: enhancement

#588 feature/wafs_fixes
  dev/drivers/scripts/plots/wafs/jevs_wafs_atmos_plots.sh
  dev/drivers/scripts/stats/wafs/jevs_wafs_atmos_stats.sh
  ecf/scripts/stats/wafs/jevs_wafs_atmos_stats.ecf
  jobs/JEVS_WAFS_PLOTS
  jobs/JEVS_WAFS_STATS
  scripts/stats/wafs/exevs_wafs_atmos_stats.sh
Labels: enhancement

#589 Adjust column lists for METv12 beta5 and fix typos
  jobs/JEVS_GLOBAL_ENS_PLOTS
  jobs/JEVS_GLOBAL_ENS_PREP
  jobs/JEVS_GLOBAL_ENS_STATS
  ush/global_ens/plot_util.py
  ush/global_ens/ush_gens_plot_py/plot_util.py
Labels: enhancement

#586 Feature/narre fixes
  dev/drivers/scripts/plots/narre/jevs_narre_last31days_plots.sh
  dev/drivers/scripts/plots/narre/jevs_narre_last90days_plots.sh
  dev/drivers/scripts/stats/narre/jevs_narre_stats.sh
  dev/modulefiles/narre/narre_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/narre/jevs_narre_last31days_plots.ecf
  ecf/scripts/plots/narre/jevs_narre_last90days_plots.ecf
  ecf/scripts/stats/narre/jevs_narre_stats.ecf
  parm/metplus_config/stats/narre/grid2obs/Pb2nc_obsRAP_Prepbufr.conf
  parm/metplus_config/stats/narre/grid2obs/PointStat_fcstNARRE_obsPREPBUFR_SFC_mean.conf
  parm/metplus_config/stats/narre/grid2obs/StatAnlysis_fcstNARRE_obsPREPBUFR_GatherByDay.conf
  scripts/plots/narre/exevs_narre_plots.sh
  ush/narre/evs_get_prepbufr.sh
  ush/narre/evs_narre_gather.sh
  ush/narre/evs_narre_stats.sh
  ush/narre/ush_narre_plot_py/prune_stat_files.py
Labels: enhancement

#590 Feature/subseasonal fixes part2
  dev/modulefiles/subseasonal/subseasonal_prep.sh
  ecf/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.ecf
  ush/subseasonal/subseasonal_prep_obs.py
  ush/subseasonal/subseasonal_util.py
Labels: enhancement

#593 Screen GEFS grid2obs Aeronet file before ASCII2NC call Feature/aeronetasciifix
  parm/metplus_config/prep/global_ens/chem_grid2obs/ASCII2NC_obsAERONET.conf
  scripts/prep/global_ens/exevs_global_ens_gefs_chem_grid2obs_prep.sh
  scripts/stats/global_ens/exevs_global_ens_chem_grid2obs_stats.sh
  ush/global_ens/screen_aeronet_aod_lev15.py
Labels: enhancement

#592 feature/EVS-GLWU_plots_initialized
  dev/drivers/scripts/plots/glwu/jevs_glwu_wave_grid2obs_plots.sh
  dev/drivers/scripts/stats/glwu/jevs_glwu_wave_grid2obs_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/glwu/jevs_glwu_wave_grid2obs_plots.ecf
  jobs/JEVS_GLWU_PLOTS
  parm/metplus_config/plots/glwu/wave_grid2obs/py_plotting_wave.config
  parm/metplus_config/stats/glwu/wave_grid2obs/PointStat_fcstGLWU_obsNDBC_climoERA5_Wave_Multifield.conf
  scripts/plots/glwu/exevs_glwu_wave_grid2obs_plots.sh
  ush/glwu/evs_wave_leadaverages.sh
  ush/glwu/evs_wave_timeseries.sh
  ush/glwu/settings.py
  ush/glwu/time_series.py
Labels: enhancement

#595 feature/EVS-NWPS_plots
  dev/drivers/scripts/plots/nwps/jevs_nwps_wave_grid2obs_plots.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/nwps/jevs_nwps_wave_grid2obs_plots.ecf
  jobs/JEVS_NWPS_PLOTS
  parm/metplus_config/plots/nwps/wave_grid2obs/py_plotting_wave.config
  scripts/plots/nwps/exevs_nwps_wave_grid2obs_plots.sh
  ush/nwps/evs_wave_leadaverages.sh
  ush/nwps/evs_wave_timeseries.sh
  ush/nwps/settings.py
Labels: enhancement

#596 add screen airnow hourly and daily obs for AQM and GEFS
  jobs/JEVS_AQM_PREP
  parm/metplus_config/prep/aqm/grid2obs/Ascii2Nc_daily_obsAIRNOW.conf
  parm/metplus_config/prep/aqm/grid2obs/Ascii2Nc_hourly_obsAIRNOW.conf
  parm/metplus_config/prep/global_ens/chem_grid2obs/ASCII2NC_obsAIRNOW.conf
  scripts/prep/aqm/exevs_aqm_prep.sh
  scripts/prep/global_ens/exevs_global_ens_gefs_chem_grid2obs_prep.sh
  ush/aqm/screen_airnow_obs_daily.py
  ush/aqm/screen_airnow_obs_hourly.py
  ush/global_ens/screen_airnow_obs_hourly.py
Labels: enhancement

#598 AQM EVS2.0 FIX Feature/fixplotcpu
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_plots.sh
  ecf/scripts/plots/aqm/jevs_aqm_plots.ecf
  scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh
Labels: enhancement
