Repository NOAA-EMC/EVS, pull requests merged in 2025-09, with the labels that each got.

#811 Add EVS AQM headline plots Feature/aqmheadline
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_headline_plots_last90days.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_headline_plots_last90days.ecf
  jobs/JEVS_AQM_PLOTS
  scripts/plots/aqm/exevs_aqm_headline_plots.sh
  ush/aqm/aqm_plots_headline.py
Labels: enhancement

#813 AQM change cpreq to cp -v
  scripts/plots/aqm/exevs_aqm_grid2grid_plots.sh
  scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh
  scripts/prep/aqm/exevs_aqm_grid2grid_prep.sh
  scripts/stats/aqm/exevs_aqm_grid2grid_stats.sh
Labels: cleanup

#822 Sample equalization for OBAR metric
  dev/drivers/scripts/plots/nfcens/jevs_plots_nfcens_wave_grid2obs_last31days.sh
  ecf/scripts/plots/nfcens/jevs_plots_nfcens_wave_grid2obs_last31days.ecf
  ush/nfcens/lead_average.py
  ush/nfcens/time_series.py
Labels: enhancement

#819 Rename AQM/PLOTS driver script and ecf scripts to include atmos
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2grid_hourly_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2grid_hourly_plots_last90days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_daily_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_daily_plots_last90days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_headline_plots_last90days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_hourly_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_hourly_plots_last90days.sh
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2grid_hourly_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2grid_hourly_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_daily_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_daily_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_headline_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_hourly_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_atmos_grid2obs_hourly_plots_last90days.ecf
Labels: Known Issue

#817 global_ens: adjust atmos grid2obs plots
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_last90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_separate_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_separate_last90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_last90days_plots.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_last90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_separate_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_separate_last90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_last90days_plots.ecf
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2grid_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_separate_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_naefs_grid2grid_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_naefs_grid2obs_plots.sh
Labels: cleanup, Known Issue

#829 Cleanup of analyses and mesoscale
  dev/drivers/scripts/plots/analyses/jevs_analyses_grid2obs_plots_last31days.sh
  dev/drivers/scripts/prep/mesoscale/jevs_mesoscale_grid2obs_prep.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_ccpa_precip_stats.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_rtma_grid2obs_stats.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_rtma_precip_stats.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_rtma_ru_grid2obs_stats.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_urma_grid2obs_stats.sh
  dev/drivers/scripts/stats/analyses/jevs_analyses_urma_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_nam_firewxnest_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_precip_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_snowfall_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_precip_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_snowfall_stats.sh
  ecf/defs/evs-nco.def
Labels: cleanup

#832 Removing some FHRs to meet PNS requirements for NFCENS component of EVS
  ush/nfcens/evs_wave_timeseries.sh
  ush/nfcens/nfcens_wave_plots_copy_plots.sh
Labels: cleanup
