Repository NOAA-EMC/EVS, pull requests merged in 2025-05, with the labels that each got.

#712 Mesoscale - fix create_child_workdirs for stats and plots
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_precip_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_snowfall_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_precip_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_snowfall_stats.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.ecf
  ush/mesoscale/mesoscale_create_child_workdirs.py
Labels: Known Issue

#714 global_ens: restart clean up for grid2grid and grid2obs stats jobs
  ush/global_ens/evs_global_ens_atmos_grid2grid.sh
  ush/global_ens/evs_global_ens_atmos_grid2obs.sh
Labels: NCO Bugzilla, cleanup

#717 AQM images title with observation source Feature/plot obs src
  jobs/JEVS_AQM_PLOTS
  ush/aqm/aqm_plots.py
  ush/aqm/aqm_plots_specs.py
Labels: enhancement

#718 GEFS-CHEM add obs src name to image title
  jobs/JEVS_GLOBAL_ENS_PLOTS
  ush/global_ens/global_ens_chem_plots.py
  ush/global_ens/global_ens_chem_plots_specs.py
Labels: enhancement

#715 sendmail is only for missing/corrupt dcom files Feature/reset email function
  scripts/prep/aqm/exevs_aqm_prep.sh
  scripts/prep/global_ens/exevs_global_ens_gefs_chem_grid2obs_prep.sh
  scripts/stats/aqm/exevs_aqm_grid2obs_stats.sh
  scripts/stats/global_ens/exevs_global_ens_chem_grid2obs_stats.sh
Labels: cleanup

#720 HREF: Adjust ncpus setting in ecnt plotting jobs
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_last31days_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_last90days_plots.sh
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_last31days_plots.ecf
  ecf/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_last90days_plots.ecf
Labels: bug

#721 Add QC flags to include all possible obs
  dev/drivers/scripts/stats/cam/jevs_cam_href_severe_stats.sh
  ecf/scripts/stats/cam/jevs_cam_href_severe_stats.ecf
  jobs/JEVS_CAM_PREP
  jobs/JEVS_CAM_STATS
  parm/metplus_config/prep/cam/severe/Point2Grid_obsSPC_PracticallyPerfect.conf
Labels: bug, Known Issue

#713 feature/EVSv2-RTOFS_plotdate_corrupted_data
  scripts/prep/rtofs/exevs_rtofs_prep.sh
  scripts/stats/rtofs/exevs_rtofs_grid2grid_stats.sh
  scripts/stats/rtofs/exevs_rtofs_grid2obs_stats.sh
  ush/rtofs/rtofs_check_nc.py
  ush/rtofs/settings.py
Labels: cleanup, Known Issue

#719 global_ens: add restart capability to atmos prep job
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_past90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_past31days_plots.sh
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2obs_past90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_past31days_plots.ecf
  jobs/JEVS_GLOBAL_ENS_PREP
  scripts/prep/global_ens/exevs_global_ens_gefs_atmos_prep.sh
  ush/global_ens/evs_global_ens_atmos_prep.sh
Labels: NCO Bugzilla

#726 AQM run script walltime adjustment
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last90days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last90days.sh
  dev/drivers/scripts/prep/aqm/jevs_aqm_prep.sh
  dev/drivers/scripts/stats/aqm/jevs_aqm_grid2obs_stats.sh
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last90days.ecf
Labels: cleanup

#722 Set cov_thresh to 0 for nbrhd stats
  parm/metplus_config/stats/cam/radar/GridStat_fcstCAM_obsMRMS_REFC.conf
  parm/metplus_config/stats/cam/radar/GridStat_fcstCAM_obsMRMS_RETOP.conf
  parm/metplus_config/stats/cam/radar/GridStat_fcstHREFPPF_obsMRMS_REFC.conf
  parm/metplus_config/stats/cam/radar/GridStat_fcstHREFPPF_obsMRMS_RETOP.conf
  parm/metplus_config/stats/cam/radar/GridStat_fcstHREFPROB_obsMRMS_REFC.conf
  parm/metplus_config/stats/cam/radar/GridStat_fcstHREFPROB_obsMRMS_RETOP.conf
Labels: bug, Known Issue

#725 Bugfix/subseasonal_read_prepbufr_fix_dev
  dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh
  dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.sh
  dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
  dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh
  ecf/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.ecf
  ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_avg.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weekly_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weekly_avg.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weeks3_4_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weeks3_4_avg.py
Labels: Known Issue

#729 feature/EVSv2-NFCENS_walltime_title
  dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.sh
  ecf/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.ecf
  ecf/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.ecf
  ush/nfcens/lead_average.py
  ush/nfcens/time_series.py
Labels: enhancement

#731 Updating walltimes for three global_ens jobs to keep parallel running
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile1_past31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile1_past90days_plots.sh
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile1_past31days_plots.ecf
Labels: cleanup

#716 Feature/tcgen
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_global_det_tcgen_plots.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_global_det_tcgen_stats.sh
  parm/metplus_config/stats/hurricane/TCGen_template.conf
  scripts/plots/hurricane/exevs_hurricane_global_det_tcgen_plots.sh
  scripts/stats/hurricane/exevs_hurricane_global_det_tcgen_stats.sh
  ush/hurricane/false_al.py
  ush/hurricane/false_ep.py
  ush/hurricane/false_wp.py
  ush/hurricane/hits_al.py
  ush/hurricane/hits_ep.py
  ush/hurricane/hits_wp.py
  ush/hurricane/tcgen_performance_diagram.py
  ush/hurricane/tcgen_space_al.py
  ush/hurricane/tcgen_space_ep.py
  ush/hurricane/tcgen_space_wp.py
Labels: cleanup

#730 HREF add validation name to plot title
  scripts/plots/cam/exevs_href_grid2obs_cape_plots.sh
  scripts/plots/cam/exevs_href_grid2obs_ctc_plots.sh
  scripts/plots/cam/exevs_href_grid2obs_ecnt_plots.sh
  scripts/plots/cam/exevs_href_precip_plots.sh
  scripts/plots/cam/exevs_href_profile_plots.sh
  scripts/plots/cam/exevs_href_snowfall_plots.sh
  scripts/plots/cam/exevs_href_spcoutlook_plots.sh
  ush/cam/ush_href_plot_py/lead_average.py
  ush/cam/ush_href_plot_py/lead_average_valid.py
  ush/cam/ush_href_plot_py/lead_average_valid_profile.py
  ush/cam/ush_href_plot_py/performance_diagram.py
  ush/cam/ush_href_plot_py/settings.py
  ush/cam/ush_href_plot_py/stat_by_level.py
  ush/cam/ush_href_plot_py/threshold_average.py
  ush/cam/ush_href_plot_py/time_series.py
  ush/cam/ush_href_plot_py/valid_hour_average.py
Labels: enhancement

#733 Update narre walltimes
  dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots_last90days.sh
  dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_sfc_plots_last31days.sh
  dev/drivers/scripts/plots/narre/jevs_narre_last31days_plots.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/narre/jevs_narre_stats.sh
  ecf/scripts/plots/cam/jevs_cam_grid2obs_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_sfc_plots_last31days.ecf
  ecf/scripts/plots/narre/jevs_narre_last31days_plots.ecf
  ecf/scripts/stats/narre/jevs_narre_stats.ecf
Labels: cleanup

#732 feature/EVSv2-RTOFS_walltime_title
  dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh
  dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_argo_grid2obs_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_grid2grid_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_grid2grid_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_ndbc_grid2obs_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_grid2grid_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_grid2grid_stats.sh
  dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_grid2grid_stats.sh
  ecf/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.ecf
  ecf/scripts/prep/rtofs/jevs_rtofs_prep.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_argo_grid2obs_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_aviso_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_ghrsst_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_ndbc_grid2obs_stats.ecf
  ush/rtofs/lead_average.py
  ush/rtofs/performance_diagram.py
  ush/rtofs/time_series.py
Labels: cleanup

#735 feature/subseasonal_prep_walltimes_memory_updates
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.sh
  ecf/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.ecf
  ecf/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.ecf
  ush/subseasonal/subseasonal_util.py
Labels: cleanup

#728 Feature/mesoscale plot split
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots_last31days.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots_last90days.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_precip_plots_last31days.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_precip_plots_last90days.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots_last31days.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots_last90days.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots_last31days.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots_last90days.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_precip_plots_last31days.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_precip_plots_last90days.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots_last31days.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots_last90days.ecf
  jobs/JEVS_MESOSCALE_PLOTS
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.grid2obs
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.precip
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.snowfall
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.snowfall.rap
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_snowfall_plots.sh
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_plots_grid2obs_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_grid2obs_graphx_defs.py
  ush/mesoscale/mesoscale_plots_precip_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_precip_graphx_defs.py
  ush/mesoscale/mesoscale_plots_snowfall_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_snowfall_graphx_defs.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/settings.py
Labels: enhancement

#734 AQM g2g abi aod verification prep and stats Feature/aqmaod
  dev/drivers/scripts/prep/aqm/jevs_aqm_atmos_grid2grid_prep.sh
  dev/drivers/scripts/prep/aqm/jevs_aqm_atmos_grid2obs_prep.sh
  dev/drivers/scripts/stats/aqm/jevs_aqm_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/aqm/jevs_aqm_atmos_grid2obs_stats.sh
  dev/modulefiles/aqm/aqm_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/prep/aqm/jevs_aqm_atmos_grid2grid_prep.ecf
  ecf/scripts/prep/aqm/jevs_aqm_atmos_grid2obs_prep.ecf
  ecf/scripts/stats/aqm/jevs_aqm_atmos_grid2grid_stats_vhr_master.ecf
  ecf/scripts/stats/aqm/jevs_aqm_atmos_grid2obs_stats_vhr_master.ecf
  jobs/JEVS_AQM_PLOTS
  jobs/JEVS_AQM_PREP
  jobs/JEVS_AQM_STATS
  parm/metplus_config/prep/aqm/grid2grid/Point2Grid_hourly_obsABI.conf
  parm/metplus_config/stats/aqm/grid2grid/GridStat_fcstAOD_obsABI.conf
  parm/metplus_config/stats/aqm/grid2grid/StatAnalysis_fcstAOD_obsABI_GatherByDay.conf
  scripts/prep/aqm/exevs_aqm_grid2grid_prep.sh
  scripts/prep/aqm/exevs_aqm_grid2obs_prep.sh
  scripts/stats/aqm/exevs_aqm_grid2grid_stats.sh
  scripts/stats/aqm/exevs_aqm_grid2obs_stats.sh
  ush/aqm/integrate_goes_east_west_aod.py
Labels: enhancement, cleanup

#737 Updating mesoscale (det) plot titles with obs source
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.ecf
  ush/mesoscale/lead_average.py
  ush/mesoscale/performance_diagram.py
  ush/mesoscale/stat_by_level.py
  ush/mesoscale/threshold_average.py
  ush/mesoscale/time_series.py
  ush/mesoscale/valid_hour_average.py
Labels: enhancement

#739 feature/subseasonal_precip_plots _walltimes
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last90days.sh
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last90days.ecf
Labels: cleanup

#740 feature/EVSv2-NFCENS_fixes_plots
  ush/nfcens/lead_average.py
  ush/nfcens/time_series.py
Labels: enhancement

#738 Feature/SREF restart and other fixes
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cape_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cloud_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cnv_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_td2m_last90days_plots.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_precip_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cape_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cloud_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_cnv_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_spatial_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_td2m_last90days_plots.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_sref_precip_stats.ecf
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstSREF_obsCCPA_prob_G212.conf
  scripts/plots/mesoscale/exevs_mesoscale_sref_cape_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cloud_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cnv_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_td2m_plots.sh
  scripts/stats/mesoscale/exevs_mesoscale_sref_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_sref_precip_stats.sh
  ush/mesoscale/evs_check_sref_files.sh
  ush/mesoscale/evs_prepare_sref.sh
  ush/mesoscale/evs_sref_cnv.sh
  ush/mesoscale/evs_sref_gather.sh
  ush/mesoscale/evs_sref_grid2obs.sh
  ush/mesoscale/evs_sref_precip.sh
  ush/mesoscale/ush_sref_plot_cnv_py/lead_average.py
Labels: Known Issue

#741 Separate GEFS-Chem Prep from GLOBAL_ENS Prep
  dev/drivers/scripts/prep/global_chem/jevs_global_chem_atmos_grid2obs_prep.sh
  dev/modulefiles/global_chem/global_chem_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/prep/global_chem/jevs_global_chem_atmos_grid2obs_prep.ecf
  jobs/JEVS_GLOBAL_CHEM_PREP
  jobs/JEVS_GLOBAL_ENS_PREP
  parm/metplus_config/prep/global_chem/atmos_grid2obs/ASCII2NC_obsAERONET.conf
  parm/metplus_config/prep/global_chem/atmos_grid2obs/ASCII2NC_obsAIRNOW.conf
  scripts/prep/global_chem/exevs_global_chem_atmos_grid2obs_prep.sh
  ush/global_chem/screen_aeronet_aod_lev15.py
  ush/global_chem/screen_airnow_obs_hourly.py
Labels: enhancement, cleanup
