Repository NOAA-EMC/EVS, pull requests merged in 2025-03, with the labels that each got.

#671 Wind direction stats and plots for global wave
  parm/metplus_config/plots/global_det/wave_grid2obs/py_plotting_wave.config
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsGDAS_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsGDAS_climoERA5_Wave_WindDir.conf
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsJASON3_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/global_det/wave_grid2obs/StatAnalysis_fcstGLOBAL_DET.conf
  scripts/plots/global_det/exevs_global_det_wave_grid2obs_plots.sh
  scripts/stats/global_det/exevs_global_det_wave_grid2obs_stats.sh
  ush/global_det/global_det_wave_plots_grid2obs_copy_plots_WindDir.sh
  ush/global_det/global_det_wave_plots_grid2obs_leadaverages_WindDir.sh
  ush/global_det/global_det_wave_plots_grid2obs_timeseries_WindDir.sh
  ush/global_det/lead_average.py
  ush/global_det/plot_util.py
  ush/global_det/settings.py
  ush/global_det/time_series.py
Labels: enhancement

#673 global_ens: change grid2obs CONUS plots x-axis from init to valid date
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2obs_separate_plots.sh
Labels: bug, cleanup

#675 feature/EVS-GLWU_MPMD
  parm/metplus_config/stats/glwu/wave_grid2obs/PointStat_fcstGLWU_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/glwu/wave_grid2obs/StatAnalysis_fcstGLWU_obsNDBC.conf
  scripts/stats/glwu/exevs_glwu_wave_grid2obs_stats.sh
Labels: NCO Bugzilla

#676 Added MPMD directories for stats.
  parm/metplus_config/stats/nfcens/wave_grid2obs/PointStat_fcstFNMOC_obsGDAS_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nfcens/wave_grid2obs/PointStat_fcstGEFS_obsGDAS_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nfcens/wave_grid2obs/PointStat_fcstNFCENS_obsGDAS_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nfcens/wave_grid2obs/StatAnalysis_fcstFNMOC_obsGDAS.conf
  parm/metplus_config/stats/nfcens/wave_grid2obs/StatAnalysis_fcstGEFS_obsGDAS.conf
  parm/metplus_config/stats/nfcens/wave_grid2obs/StatAnalysis_fcstNFCENS_obsGDAS.conf
  scripts/stats/nfcens/exevs_nfcens_wave_grid2obs_stats.sh
Labels: NCO Bugzilla

#677 Added MPMD directories for EVS-NWPS stats
  parm/metplus_config/stats/nwps/wave_grid2obs/PointStat_fcstNWPS_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/StatAnalysis_fcstNWPS_obsNDBC.conf
  scripts/stats/nwps/exevs_nwps_wave_grid2obs_stats.sh
Labels: NCO Bugzilla

#679 global_ens: fix CAPE configurations and mismatch variables
  parm/metplus_config/stats/global_ens/atmos_grid2obs/EnsembleStat_fcstCMCE_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/EnsembleStat_fcstGEFS_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/EnsembleStat_fcstGEFS_obsPREPBUFR_CLOUD_F000.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/EnsembleStat_fcstNAEFS_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/GenEnsProd_fcstCMCE_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/GenEnsProd_fcstGEFS_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/GenEnsProd_fcstGEFS_obsPREPBUFR_CLOUD_F000.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/GenEnsProd_fcstNAEFS_obsPREPBUFR_CLOUD.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstCMCE_obsPREPBUFR_CLOUD_mean.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstCMCE_obsPREPBUFR_CLOUD_prob.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstGEFS_obsPREPBUFR_CLOUD_mean.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstGEFS_obsPREPBUFR_CLOUD_mean_F000.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstGEFS_obsPREPBUFR_CLOUD_prob.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstGEFS_obsPREPBUFR_CLOUD_prob_F000.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstNAEFS_obsPREPBUFR_CLOUD_mean.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/PointStat_fcstNAEFS_obsPREPBUFR_CLOUD_prob.conf
Labels: Known Issue

#681 feature/EVSv2-RTOFS_additions_part1
  ecf/defs/evs-nco.def
  ecf/scripts/stats/rtofs/jevs_rtofs_argo_grid2obs_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_aviso_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_ghrsst_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_ndbc_grid2obs_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_osisaf_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_smap_grid2grid_stats.ecf
  ecf/scripts/stats/rtofs/jevs_rtofs_smos_grid2grid_stats.ecf
  jobs/JEVS_RTOFS_STATS
  parm/metplus_config/prep/rtofs/grid2obs/ASCII2NC_obsARGO.conf
  parm/metplus_config/prep/rtofs/grid2obs/ASCII2NC_obsNDBC.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsAVISO_climoHYCOM.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsGHRSST_climoWOA23.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsOSISAF_nh.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsOSISAF_sh.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsSMAP_climoWOA23.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsSMOS_climoWOA23.conf
  parm/metplus_config/stats/rtofs/grid2obs/PointStat_fcstRTOFS_obsARGO_climoWOA23_psal.conf
  parm/metplus_config/stats/rtofs/grid2obs/PointStat_fcstRTOFS_obsARGO_climoWOA23_temp.conf
  parm/metplus_config/stats/rtofs/grid2obs/PointStat_fcstRTOFS_obsNDBC_climoWOA23.conf
  scripts/prep/rtofs/exevs_rtofs_prep.sh
  scripts/stats/rtofs/exevs_rtofs_grid2grid_stats.sh
  scripts/stats/rtofs/exevs_rtofs_grid2obs_stats.sh
  ush/rtofs/rtofs_prep_regions.sh
  ush/rtofs/rtofs_prep_trim_ndbc_files.py
Labels: Known Issue

#672 RRFS-Chem Prep and Stats step - Feature/rrfs pr
  dev/drivers/scripts/prep/cam/jevs_cam_rrfs_chem_grid2obs_prep.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_aeronet_aod_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_airnow_pm10_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_airnow_pm25_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/prep/cam/jevs_cam_rrfs_chem_grid2obs_prep.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_aeronet_aod_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_airnow_pm10_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_rrfs_chem_grid2obs_airnow_pm25_stats_vhr_master.ecf
  jobs/JEVS_CAM_PREP
  jobs/JEVS_CAM_STATS
  parm/metplus_config/prep/cam/chem_grid2obs/ASCII2NC_obsAERONET.conf
  parm/metplus_config/prep/cam/chem_grid2obs/ASCII2NC_obsAIRNOW.conf
  parm/metplus_config/stats/cam/chem_grid2obs/PointStat_fcstRRFSAero_obsAERONET_AOD.conf
  parm/metplus_config/stats/cam/chem_grid2obs/PointStat_fcstRRFSAero_obsAIRNOW_PM10.conf
  parm/metplus_config/stats/cam/chem_grid2obs/PointStat_fcstRRFSAero_obsAIRNOW_PM25.conf
  parm/metplus_config/stats/cam/chem_grid2obs/Statanalysis_fcstRRFSAero_obsAERONET_AOD.conf
  parm/metplus_config/stats/cam/chem_grid2obs/Statanalysis_fcstRRFSAero_obsAIRNOW_PM10.conf
  parm/metplus_config/stats/cam/chem_grid2obs/Statanalysis_fcstRRFSAero_obsAIRNOW_PM25.conf
  scripts/prep/cam/exevs_cam_rrfs_chem_grid2obs_prep.sh
  scripts/stats/cam/exevs_cam_rrfs_chem_grid2obs_stats.sh
  ush/cam/cam_chem_screen_aeronet_aod_lev15.py
  ush/cam/cam_chem_screen_airnow_obs_hourly.py
Labels: enhancement

#683 Feature/subseasonal precip plots
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_90days.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_90days.ecf
  parm/evs_config/subseasonal/config.evs.subseasonal.grid2grid.plots.precip
  scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh
  ush/subseasonal/check_subseasonal_config_plots.py
  ush/subseasonal/subseasonal_plots.py
  ush/subseasonal/subseasonal_plots_grid2grid_create_job_scripts.py
  ush/subseasonal/subseasonal_plots_lead_average.py
  ush/subseasonal/subseasonal_plots_performance_diagram.py
  ush/subseasonal/subseasonal_plots_specs.py
  ush/subseasonal/subseasonal_plots_time_series.py
Labels: enhancement

#685 global_ens: add precip BSS, RMSE, and bias plots
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_precip_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_naefs_precip_plots.sh
  ush/global_ens/ush_gens_plot_py/lead_average.py
  ush/global_ens/ush_gens_plot_py/settings.py
  ush/global_ens/ush_gens_plot_py/time_series.py
Labels: enhancement

#678 GEFS-Chem Plots to support both operational and developmental evaluation Feature/gef splotsadd
  jobs/JEVS_GLOBAL_ENS_PLOTS
  parm/evs_config/global_ens/config.evs.prod.plots.global_ens.chem.grid2obs.aeronet
  parm/evs_config/global_ens/config.evs.prod.plots.global_ens.chem.grid2obs.airnow
  parm/metplus_config/prep/global_ens/chem_grid2obs/ASCII2NC_obsAERONET.conf
  parm/metplus_config/prep/global_ens/chem_grid2obs/ASCII2NC_obsAIRNOW.conf
  parm/metplus_config/stats/global_ens/chem_grid2obs/PointStat_fcstGEFSAero_obsAERONET.conf
  parm/metplus_config/stats/global_ens/chem_grid2obs/PointStat_fcstGEFSAero_obsAIRNOW.conf
  parm/metplus_config/stats/global_ens/chem_grid2obs/Statanalysis_fcstGEFSAero_obsAERONET.conf
  parm/metplus_config/stats/global_ens/chem_grid2obs/Statanalysis_fcstGEFSAero_obsAIRNOW.conf
  scripts/plots/global_ens/exevs_global_ens_chem_gefs_grid2obs_plots.sh
  scripts/prep/global_ens/exevs_global_ens_gefs_chem_grid2obs_prep.sh
  scripts/stats/global_ens/exevs_global_ens_chem_grid2obs_stats.sh
  ush/global_ens/global_ens_chem_check_settings.py
  ush/global_ens/global_ens_chem_copy_job_dir_output.py
  ush/global_ens/global_ens_chem_create_output_dirs.py
  ush/global_ens/global_ens_chem_get_data_files.py
  ush/global_ens/global_ens_chem_plots.py
  ush/global_ens/global_ens_chem_plots_grid2obs_create_job_scripts.py
  ush/global_ens/global_ens_chem_plots_lead_average.py
  ush/global_ens/global_ens_chem_plots_performance_diagram.py
  ush/global_ens/global_ens_chem_plots_specs.py
  ush/global_ens/global_ens_chem_plots_threshold_average.py
  ush/global_ens/global_ens_chem_plots_time_series.py
  ush/global_ens/global_ens_chem_plots_valid_hour_average.py
  ush/global_ens/global_ens_chem_util.py
  ush/global_ens/screen_airnow_obs_hourly.py
Labels: cleanup

#686 feature/EVS-GLWU_plots_mpmd
  parm/metplus_config/plots/glwu/wave_grid2obs/py_plotting_wave.config
  scripts/plots/glwu/exevs_glwu_wave_grid2obs_plots.sh
  ush/glwu/evs_wave_leadaverages.sh
  ush/glwu/evs_wave_timeseries.sh
  ush/glwu/glwu_wave_plots_copy_plots.sh
  ush/glwu/lead_average.py
  ush/glwu/time_series.py
Labels: NCO Bugzilla

#689 feature/EVSv2-NFCENS_plots_mpmd
  parm/metplus_config/plots/nfcens/wave_grid2obs/py_plotting_wave.config
  scripts/plots/nfcens/exevs_nfcens_wave_grid2obs_plots.sh
  ush/nfcens/evs_wave_leadaverages.sh
  ush/nfcens/evs_wave_timeseries.sh
  ush/nfcens/lead_average.py
  ush/nfcens/nfcens_wave_plots_copy_plots.sh
  ush/nfcens/time_series.py
Labels: NCO Bugzilla

#688 AQM Plots step for OPS and DEV evaluation Feature/devaqmverif
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last90days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last31days.sh
  dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last90days.sh
  dev/modulefiles/aqm/aqm_plots.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last90days.ecf
  jobs/JEVS_AQM_PLOTS
  jobs/JEVS_AQM_PREP
  jobs/JEVS_AQM_STATS
  parm/evs_config/aqm/config.evs.aqm.prod
  parm/evs_config/aqm/config.evs.prod.plots.aqm.grid2obs.daily
  parm/evs_config/aqm/config.evs.prod.plots.aqm.grid2obs.hourly
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_awpozcon.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_awpozcon_fbar.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_ozmax8.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_ozmax8_headline.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_pm25.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_pm25_fbar.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_pmave.config
  parm/metplus_config/plots/aqm/grid2obs/py_plotting_pmave_headline.config
  scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh
  ush/aqm/aqm_check_settings.py
  ush/aqm/aqm_copy_job_dir_output.py
  ush/aqm/aqm_create_output_dirs.py
  ush/aqm/aqm_get_data_files.py
  ush/aqm/aqm_plots.py
  ush/aqm/aqm_plots_grid2obs_create_job_scripts.py
  ush/aqm/aqm_plots_lead_average.py
  ush/aqm/aqm_plots_lead_average_vhr_mean.py
  ush/aqm/aqm_plots_performance_diagram.py
  ush/aqm/aqm_plots_specs.py
  ush/aqm/aqm_plots_threshold_average.py
  ush/aqm/aqm_plots_time_series.py
  ush/aqm/aqm_plots_time_series_fhr_mean.py
  ush/aqm/aqm_plots_valid_hour_average.py
  ush/aqm/aqm_plots_valid_hour_average_fhr_mean.py
  ush/aqm/aqm_util.py
  ush/aqm/check_variables.py
  ush/aqm/df_preprocessing.py
  ush/aqm/lead_average.py
  ush/aqm/performance_diagram.py
  ush/aqm/plot_util.py
  ush/aqm/plotter.py
  ush/aqm/prune_stat_files.py
  ush/aqm/roc_curve.py
  ush/aqm/screen_airnow_obs_daily.py
  ush/aqm/screen_airnow_obs_hourly.py
  ush/aqm/settings.py
  ush/aqm/spatial_map.py
  ush/aqm/stat_by_level.py
  ush/aqm/string_template_substitution.py
  ush/aqm/threshold_average.py
  ush/aqm/time_series.py
  ush/aqm/time_util.py
  ush/aqm/valid_hour_average.py
Labels: enhancement, cleanup

#690 Updating met and metplus versions
  versions/run.ver
Labels: enhancement

#691 Feature/subseasonal plot changes
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last90days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_last90days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_last90days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_last90days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_last90days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_last31days.sh
  dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_last90days.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_precip_plots_last90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_last90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_last90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_last90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_last90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_last31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_last90days.ecf
  ush/subseasonal/subseasonal_plots_specs.py
Labels: enhancement
