Repository NOAA-EMC/EVS, pull requests merged in 2025-04, with the labels that each got.

#696 Set GRID_STAT_OUTPUT_FLAG_FHO to NONE
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obs24hrCCPA.conf
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obs24hrNOHRSC.conf
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obs3hrCCPA.conf
Labels: cleanup

#693 Corresponding changes due to RRFS NRT filename changes update grib2 filename
  scripts/prep/cam/exevs_cam_rrfs_chem_grid2obs_prep.sh
Labels: cleanup

#699 feature/EVSv2-NFCENS_ecf_update
  ecf/defs/evs-nco.def
Labels: cleanup

#692 Feature/narre MPMD
  dev/drivers/scripts/plots/narre/jevs_narre_last31days_plots.sh
  dev/drivers/scripts/plots/narre/jevs_narre_last90days_plots.sh
  dev/drivers/scripts/stats/narre/jevs_narre_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/narre/jevs_narre_last31days_plots.ecf
  ecf/scripts/plots/narre/jevs_narre_last90days_plots.ecf
  ecf/scripts/stats/narre/jevs_narre_stats.ecf
  jobs/JEVS_NARRE_PLOTS
  jobs/JEVS_NARRE_STATS
  scripts/plots/narre/exevs_narre_plots.sh
  scripts/stats/narre/exevs_narre_stats.sh
  ush/narre/evs_get_prepbufr.sh
  ush/narre/evs_narre_gather.sh
  ush/narre/evs_narre_stats.sh
  ush/narre/ush_narre_plot_py/lead_average.py
Labels: NCO Bugzilla

#698 feature/EVS-NWPS_plots_mpmd
  parm/metplus_config/plots/nwps/wave_grid2obs/py_plotting_wave.config
  scripts/plots/nwps/exevs_nwps_wave_grid2obs_plots.sh
  ush/nwps/evs_wave_leadaverages.sh
  ush/nwps/evs_wave_timeseries.sh
  ush/nwps/lead_average.py
  ush/nwps/nwps_wave_plots_copy_plots.sh
  ush/nwps/time_series.py
Labels: NCO Bugzilla

#694 global_ens: add restart capability to atmos grid2obs stats jobs
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_precip_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_precip_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_precip_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_precip_stats.sh
  ecf/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_precip_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_precip_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_grid2obs_stats.ecf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/StatAnlysis_fcstGENS_obsPREPBUFR_CNV_GatherByDay.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/StatAnlysis_fcstGENS_obsPREPBUFR_GatherByDay.conf
  ush/global_ens/evs_global_ens_atmos_grid2grid.sh
  ush/global_ens/evs_global_ens_atmos_grid2obs.sh
Labels: NCO Bugzilla

#695 Feature/mesoscale completed jobs
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.nam
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.rap
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
Labels: cleanup

#701 Feature/fixes 042025
  jobs/JEVS_HURRICANE_PLOTS
  jobs/JEVS_HURRICANE_STATS
  scripts/stats/hurricane/exevs_hurricane_global_det_tcgen_stats.sh
  scripts/stats/hurricane/exevs_hurricane_global_det_tropcyc_stats.sh
  scripts/stats/hurricane/exevs_hurricane_global_ens_spread_stats.sh
  scripts/stats/hurricane/exevs_hurricane_global_ens_tropcyc_stats.sh
  scripts/stats/hurricane/exevs_hurricane_regional_tropcyc_stats.sh
Labels: enhancement

#702 bugfix/EVS-GLWU
  parm/metplus_config/plots/glwu/wave_grid2obs/py_plotting_wave.config
  scripts/plots/glwu/exevs_glwu_wave_grid2obs_plots.sh
  ush/glwu/df_preprocessing.py
Labels: bug, cleanup

#704 Feature/subseasonal add obs in plot titles
  ush/subseasonal/subseasonal_plots.py
  ush/subseasonal/subseasonal_plots_specs.py
Labels: enhancement

#705 bugfix/EVS-NWPS
  ush/nwps/df_preprocessing.py
Labels: Known Issue

#706 global_ens: add restart capability to atmos snowfall and cnv stats jobs
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_snowfall_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_snowfall_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_cnv_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_snowfall_stats.sh
  ecf/scripts/stats/global_ens/jevs_global_ens_cmce_atmos_snowfall_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_ecme_atmos_snowfall_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_cnv_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_snowfall_stats.ecf
  ush/global_ens/evs_global_ens_atmos_cnv.sh
  ush/global_ens/evs_global_ens_atmos_snowfall.sh
Labels: NCO Bugzilla

#708 Mesoscale (NAM/RAP) stats restart fix
  scripts/stats/mesoscale/exevs_mesoscale_nam_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_grid2obs_stats.sh
  ush/mesoscale/mesoscale_create_child_workdirs.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_poe_job_scripts.py
Labels: NCO Bugzilla

#711 feature/sref_increase precip plot walltime
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.ecf
Labels: bug
