Repository NOAA-EMC/EVS, pull requests merged in 2025-02, with the labels that each got.

#661 bugfix/ops_fix_ghrsst
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obsGHRSST_OSPO_DailyAvg.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/EnsembleStat_fcstGEFS_obsGHRSST.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsGHRSST_climoWOA23.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_DailyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_MonthlyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_WeeklyAvg.conf
Labels: bug

#662 bugfix/dev_fix_ghrsst
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obsGHRSST_OSPO_DailyAvg.conf
  parm/metplus_config/stats/global_ens/atmos_grid2grid/EnsembleStat_fcstGEFS_obsGHRSST.conf
  parm/metplus_config/stats/rtofs/grid2grid/GridStat_fcstRTOFS_obsGHRSST_climoWOA23.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_DailyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_MonthlyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_WeeklyAvg.conf
Labels: bug

#660 Global-det SST sea ice fix
  parm/metplus_config/stats/global_det/atmos_grid2grid/GridStat_fcstGLOBAL_DET_obsGHRSST_OSPO_DailyAvg.conf
  ush/global_det/global_det_atmos_plots_grid2grid_create_job_scripts.py
  ush/global_det/global_det_atmos_plots_specs.py
Labels: enhancement

#663 bugfix/long_term_stats
  ush/global_det/global_det_atmos_stats_long_term.py
Labels: bug

#664 GEFS -CHEM PLOTS MPMD BUGFIX - Feature/gef splotmpmd
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_aeronet_plots_last31days.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_aeronet_plots_last90days.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_airnow_plots_last31days.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_airnow_plots_last90days.sh
  ecf/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_aeronet_plots_last31days.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_aeronet_plots_last90days.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_airnow_plots_last31days.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_chem_gefs_grid2obs_airnow_plots_last90days.ecf
  scripts/plots/global_ens/exevs_global_ens_chem_gefs_grid2obs_plots.sh
  ush/global_ens/global_ens_chem_check_settings.py
  ush/global_ens/global_ens_chem_copy_job_dir_output.py
  ush/global_ens/global_ens_chem_create_output_dirs.py
  ush/global_ens/global_ens_chem_get_data_files.py
  ush/global_ens/global_ens_chem_plots.py
  ush/global_ens/global_ens_chem_plots_grid2obs_create_job_scripts.py
  ush/global_ens/global_ens_chem_plots_lead_average.py
  ush/global_ens/global_ens_chem_plots_performance_diagram.py
  ush/global_ens/global_ens_chem_plots_production_tof120.py
  ush/global_ens/global_ens_chem_plots_specs.py
  ush/global_ens/global_ens_chem_plots_threshold_average.py
  ush/global_ens/global_ens_chem_plots_time_series.py
  ush/global_ens/global_ens_chem_plots_valid_hour_average.py
  ush/global_ens/global_ens_chem_util.py
Labels: NCO Bugzilla

#666 feature/dev_eo_14172
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsNDBC_climoERA5_Wave_Multifield.conf
  parm/metplus_config/stats/nwps/wave_grid2obs/PointStat_fcstNWPS_obsNDBC_climoERA5_Wave_Multifield.conf
  ush/analyses/settings.py
  ush/aqm/settings.py
  ush/cam/settings.py
  ush/cam/ush_href_plot_py/settings.py
  ush/global_det/global_det_wave_plots_grid2obs_copy_plots.sh
  ush/global_det/global_det_wave_plots_grid2obs_leadaverages.sh
  ush/global_det/global_det_wave_plots_grid2obs_timeseries.sh
  ush/global_det/settings.py
  ush/global_ens/settings.py
  ush/global_ens/ush_gens_plot_py/settings.py
  ush/glwu/settings.py
  ush/mesoscale/settings.py
  ush/mesoscale/ush_sref_plot_cnv_py/settings.py
  ush/mesoscale/ush_sref_plot_precip_py/settings.py
  ush/mesoscale/ush_sref_plot_py/settings.py
  ush/narre/ush_narre_plot_py/settings.py
  ush/nfcens/settings.py
  ush/nwps/settings.py
  ush/rtofs/settings.py
  ush/wafs/evs_wafs_atmos_plot_settings.py
Labels: update

#667 feature/ops_eo_14172
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsNDBC_climoERA5_Wave_Multifield.conf
  ush/analyses/settings.py
  ush/analyses/settings.py_orig
  ush/aqm/settings.py
  ush/cam/settings.py
  ush/cam/ush_href_plot_py/settings.py
  ush/global_det/global_det_wave_plots_grid2obs_leadaverages.sh
  ush/global_det/global_det_wave_plots_grid2obs_timeseries.sh
  ush/global_det/settings.py
  ush/global_ens/settings.py
  ush/global_ens/ush_gens_plot_py/settings.py
  ush/mesoscale/settings.py
  ush/mesoscale/ush_sref_plot_cnv_py/settings.py
  ush/mesoscale/ush_sref_plot_precip_py/settings.py
  ush/mesoscale/ush_sref_plot_py/settings.py
  ush/narre/ush_narre_plot_py/settings.py
  ush/nfcens/settings.py
  ush/rtofs/settings.py
Labels: update

#668 global_ens: SST ice fix
  parm/metplus_config/stats/global_ens/atmos_grid2grid/EnsembleStat_fcstGEFS_obsGHRSST.conf
Labels: enhancement

#669 2024tc-all-models
  scripts/plots/hurricane/exevs_hurricane_global_det_tropcyc_plots.sh
  scripts/plots/hurricane/exevs_hurricane_regional_tropcyc_plots.sh
  scripts/stats/hurricane/exevs_hurricane_global_det_tropcyc_stats.sh
  scripts/stats/hurricane/exevs_hurricane_regional_tropcyc_stats.sh
Labels: enhancement

#670 Feature/mesoscale mpmd g2g
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstMESOSCALE_obsCCPA.conf
  parm/metplus_config/stats/mesoscale/precip/GridStat_fcstMESOSCALE_obsMRMS.conf
  parm/metplus_config/stats/mesoscale/precip/PcpCombine_fcstMESOSCALE_APCP.conf
  parm/metplus_config/stats/mesoscale/precip/PcpCombine_obsCCPA.conf
  parm/metplus_config/stats/mesoscale/precip/StatAnalysis_fcstMESOSCALE.conf
  parm/metplus_config/stats/mesoscale/snowfall/GridStat_fcstMESOSCALE_obsNOHRSC.conf
  parm/metplus_config/stats/mesoscale/snowfall/PcpCombine_fcstMESOSCALE_snow_vars.conf
  parm/metplus_config/stats/mesoscale/snowfall/StatAnalysis_fcstMESOSCALE.conf
  scripts/stats/mesoscale/exevs_mesoscale_nam_precip_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_nam_snowfall_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_precip_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_snowfall_stats.sh
  ush/mesoscale/mesoscale_copy_job_dir_output.py
  ush/mesoscale/mesoscale_precip_stats_create_job_scripts.py
  ush/mesoscale/mesoscale_precip_stats_get_data.py
  ush/mesoscale/mesoscale_snowfall_stats_create_job_scripts.py
  ush/mesoscale/mesoscale_snowfall_stats_get_data.py
  ush/mesoscale/mesoscale_util.py
Labels: NCO Bugzilla
