Repository NOAA-EMC/EVS, pull requests merged in 2025-01, with the labels that each got.

#640 bugfix for intel_ver in aqm /dev/driver scripts
  dev/modulefiles/aqm/aqm_prep.sh
  dev/modulefiles/aqm/aqm_stats.sh
  ecf/scripts/prep/aqm/jevs_aqm_prep.ecf
  ecf/scripts/stats/aqm/jevs_aqm_stats_vhr_master.ecf
Labels: cleanup

#639 feature/global_det_rc1
  dev/drivers/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_cmc_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_wmo_daily_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_imd_atmos_grid2grid_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_imd_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_ukmet_atmos_grid2obs_stats.sh
  ecf/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_cfs_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_cmc_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_cmc_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_ecmwf_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_atmos_wmo_daily_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_imd_atmos_grid2grid_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_ukmet_atmos_grid2obs_stats.ecf
  ush/global_det/global_det_atmos_stats_grid2grid_create_anomaly.py
  ush/global_det/global_det_atmos_stats_grid2obs_create_anomaly.py
  ush/global_det/global_det_atmos_stats_grid2obs_create_daily_avg.py
  versions/run.ver
Labels: enhancement

#621 Feature/subseasonal METplus rc1 changes
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.sh
  dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_90days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.ecf
  ecf/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_90days.ecf
  ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_avg.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weekly_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weekly_avg.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weeks3_4_anomaly.py
  ush/subseasonal/subseasonal_stats_grid2obs_create_weeks3_4_avg.py
Labels: enhancement

#620 Feature/2024updates
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_global_det_tcgen_plots.sh
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_global_det_tropcyc_plots.sh
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_global_ens_spread_plots.sh
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_global_ens_tropcyc_plots.sh
  dev/drivers/scripts/plots/hurricane/jevs_hurricane_regional_tropcyc_plots.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_global_det_tcgen_stats.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_global_det_tropcyc_stats.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_global_ens_spread_stats.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_global_ens_tropcyc_stats.sh
  dev/drivers/scripts/stats/hurricane/jevs_hurricane_regional_tropcyc_stats.sh
  dev/modulefiles/hurricane/hurricane_plots.sh
  dev/modulefiles/hurricane/hurricane_stats.sh
  jobs/JEVS_HURRICANE_PLOTS
  jobs/JEVS_HURRICANE_STATS
  scripts/plots/hurricane/exevs_hurricane_global_det_tropcyc_plots.sh
  scripts/plots/hurricane/exevs_hurricane_global_ens_tropcyc_plots.sh
  scripts/plots/hurricane/exevs_hurricane_regional_tropcyc_plots.sh
  scripts/stats/hurricane/exevs_hurricane_global_det_tropcyc_stats.sh
  scripts/stats/hurricane/exevs_hurricane_global_ens_spread_stats.sh
  scripts/stats/hurricane/exevs_hurricane_global_ens_tropcyc_stats.sh
  scripts/stats/hurricane/exevs_hurricane_regional_tropcyc_stats.sh
  ush/hurricane/plot_tropcyc_lead_average.py
Labels: enhancement

#641 feature/rrfs_refs_v1_parm_cleanup
  parm/metplus_config/stats/cam/grid2obs/Pb2nc_obsGDAS_Prepbufr_refs_profile.conf
  parm/metplus_config/stats/cam/grid2obs/Pb2nc_obsRAP_Prepbufr_refs_profile.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstRRFS_FIREWXNEST_obsPREPBUFR.conf
  parm/metplus_config/stats/cam/grid2obs/StatAnalysis_fcstRRFS_FIREWXNEST_obsADPUPA_GatherByDay.conf
  parm/metplus_config/stats/cam/grid2obs/StatAnalysis_fcstRRFS_FIREWXNEST_obsONLYSF_GatherByDay.conf
Labels: cleanup

#645 Bugzilla 1606: Fixed the plots codes to prevent potential failure.
  ush/glwu/lead_average.py
  ush/glwu/time_series.py
Labels: NCO Bugzilla

#643 feature/rm_cpreq
  .github/pull_request_template.md
  dev/drivers/scripts/plots/cam/jevs_cam_radar_plots.sh
  dev/drivers/scripts/plots/cam/jevs_cam_severe_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_precip_plots.sh
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_href_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_hrrr_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_namnest_severe_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_radar_prep.sh
  dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_headline_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_precip_plots.ecf
  ecf/scripts/plots/mesoscale/jevs_mesoscale_snowfall_plots.ecf
  parm/metplus_config/prep/global_ens/wave_grid2obs/PB2NC_wave.conf
  scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh
  scripts/plots/global_ens/exevs_global_ens_wave_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_headline_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_snowfall_plots.sh
  scripts/prep/cam/exevs_href_severe_prep.sh
  scripts/prep/global_ens/exevs_global_ens_wave_grid2obs_prep.sh
  scripts/stats/aqm/exevs_aqm_grid2obs_stats.sh
  scripts/stats/global_ens/exevs_global_ens_chem_grid2obs_stats.sh
  scripts/stats/global_ens/exevs_global_ens_wave_grid2obs_stats.sh
  ush/global_ens/evs_get_gens_atmos_data.sh
  ush/global_ens/evs_get_gens_headline_data.sh
Labels: cleanup

#648 Missing array1606
  dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_long_term_stats.sh
  ush/global_det/lead_average.py
  ush/global_det/time_series.py
Labels: NCO Bugzilla

#649 Bugfix/global-det wave (Bug #1586)
  ush/global_det/plot_util.py
Labels: NCO Bugzilla

#650 Bugfix/EVS-NWPS_1606
  scripts/plots/nwps/exevs_nwps_wave_grid2obs_plots.sh
  ush/nwps/lead_average.py
  ush/nwps/time_series.py
Labels: NCO Bugzilla

#651 feature/cm_setup_ecf_link_global_ens_chem
  ecf/setup_ecf_links.sh
Labels: enhancement

#653 2024 global_ens with UKMN
  scripts/plots/hurricane/exevs_hurricane_global_ens_tropcyc_plots.sh
  scripts/stats/hurricane/exevs_hurricane_global_ens_tropcyc_stats.sh
Labels: enhancement

#654 feature/cm jjob
  jobs/JEVS_CAM_PLOTS
  jobs/JEVS_CAM_PREP
  jobs/JEVS_CAM_STATS
  jobs/JEVS_GLOBAL_ENS_WAVE_GRID2OBS_PLOTS
  jobs/JEVS_GLOBAL_ENS_WAVE_GRID2OBS_PREP
  jobs/JEVS_GLOBAL_ENS_WAVE_GRID2OBS_STATS
  jobs/JEVS_NARRE_PLOTS
  jobs/JEVS_NARRE_STATS
Labels: cleanup

#657 Feature/subseasonal sst ice fix
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_DailyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_MonthlyAvg.conf
  parm/metplus_config/stats/subseasonal/grid2grid/GridStat_fcstSUBSEASONAL_obsGHRSST_OSPO_WeeklyAvg.conf
  ush/subseasonal/subseasonal_plots_grid2grid_create_job_scripts.py
  ush/subseasonal/subseasonal_plots_specs.py
  ush/subseasonal/subseasonal_util.py
Labels: enhancement

#658 feature/dev_evs_v1.0.17
  dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.sh
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.sh
  dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.sh
  ecf/scripts/stats/cam/jevs_cam_href_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats.ecf
  ecf/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.ecf
  ecf/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.ecf
  ecf/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.ecf
  jobs/JEVS_WAFS_STATS
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGCIP.conf
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGFS.conf
  ush/global_det/lead_average.py
  ush/global_det/time_series.py
  ush/wafs/evs_wafs_atmos_stats_preparedata.sh
  versions/run.ver
Labels: update

#652 Feature/mesoscale restart NAM/RAP stats
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.nam
  parm/evs_config/mesoscale/config.evs.prod.stats.mesoscale.atmos.grid2obs.rap
  scripts/stats/mesoscale/exevs_mesoscale_nam_grid2obs_stats.sh
  scripts/stats/mesoscale/exevs_mesoscale_rap_grid2obs_stats.sh
  ush/mesoscale/mesoscale_check_settings.py
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_util.py
Labels: NCO Bugzilla
