Repository NOAA-EMC/EVS, pull requests merged in 2025-07, with the labels that each got.

#779 Analyses precip ccpa fix
  dev/drivers/scripts/stats/analyses/jevs_analyses_ccpa_precip_stats.sh
  parm/metplus_config/stats/analyses/precip/PointStat_fcstCCPA_obsCOCORAHS_ASCIIprecip.conf
  scripts/stats/analyses/exevs_analyses_ccpa_precip_stats.sh
Labels: bug

#781 global_ens: fix Bugzilla 1606 and subprocess syntax
  ush/global_ens/global_ens_atmos_util.py
  ush/global_ens/ush_gens_plot_py/global_det_atmos_util.py
  ush/global_ens/ush_gens_plot_py/lead_average.py
  ush/global_ens/ush_gens_plot_py/plot_util.py
  ush/global_ens/ush_gens_plot_py/stat_by_level.py
  ush/global_ens/ush_gens_plot_py/time_series.py
Labels: NCO Bugzilla

#772 Remove JMA QPF verification from EVS v2.0
  jobs/JEVS_GLOBAL_DET_PREP
  parm/evs_config/global_det/config.evs.prod.plots.global_det.atmos.grid2grid.precip
  parm/evs_config/global_det/config.evs.prod.stats.global_det.atmos.grid2grid.jma
  ush/global_det/global_det_atmos_prep.py
Labels: cleanup

#782 Analyses stats COMOUTfinal adjustment
  jobs/JEVS_ANALYSES_STATS
  scripts/stats/analyses/exevs_analyses_ccpa_precip_stats.sh
  scripts/stats/analyses/exevs_analyses_rtma_grid2obs_stats.sh
  scripts/stats/analyses/exevs_analyses_rtma_precip_stats.sh
  scripts/stats/analyses/exevs_analyses_rtma_ru_grid2obs_stats.sh
  scripts/stats/analyses/exevs_analyses_urma_grid2obs_stats.sh
  scripts/stats/analyses/exevs_analyses_urma_precip_stats.sh
Labels: bug, cleanup

#775 NAM and RAP stats fix for restart for ptype
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
Labels: bug

#776 Removing "not" from mesoscale plot job output
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_headline_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_snowfall_plots.sh
  ush/mesoscale/check_variables.py
  ush/mesoscale/mesoscale_create_child_workdirs.py
Labels: cleanup

#785 NAM/RAP - spc outlook grid2obs fixes/adding raob stats into RAP
  scripts/stats/mesoscale/exevs_mesoscale_rap_grid2obs_stats.sh
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
Labels: bug

#784 Analyses plots - remove WARNING statements for missing plots
  scripts/plots/analyses/exevs_analyses_grid2obs_plots.sh
  ush/analyses/time_series.py
Labels: cleanup

#786 NAM/RAP adjust stats grid2obs runtime and spc outlook updates
  dev/drivers/scripts/prep/mesoscale/jevs_mesoscale_grid2obs_prep.sh
  dev/modulefiles/mesoscale/mesoscale_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/prep/mesoscale/jevs_mesoscale_grid2obs_prep.ecf
  jobs/JEVS_MESOSCALE_PREP
  jobs/JEVS_MESOSCALE_STATS
  parm/metplus_config/prep/mesoscale/grid2obs/GenVxMask_SPC_OTLK.conf
  scripts/prep/mesoscale/exevs_mesoscale_grid2obs_prep.sh
  ush/mesoscale/evs_prep_spc_otlk.py
Labels: enhancement, cleanup

#787 Analyses precip - check for corrupt dcom files
  scripts/stats/analyses/exevs_analyses_ccpa_precip_stats.sh
  scripts/stats/analyses/exevs_analyses_rtma_precip_stats.sh
  scripts/stats/analyses/exevs_analyses_urma_precip_stats.sh
  ush/analyses/check_csv.py
Labels: enhancement
