Repository NOAA-EMC/EVS, pull requests merged in 2025-06, with the labels that each got.

#744 global_ens: modify atmos prep job for MPMD processes
  scripts/prep/global_ens/exevs_global_ens_gefs_atmos_prep.sh
  ush/global_ens/evs_get_gens_atmos_data.sh
  ush/global_ens/evs_process_atmos_ecme.sh
  ush/global_ens/global_ens_atmos_util.py
  ush/global_ens/global_ens_prep_ghrsst_obs.py
  ush/global_ens/global_ens_sea_ice_prep.py
Labels: NCO Bugzilla

#748 Separate GEFS-Chem Stats from GLOBAL_ENS Stats
  dev/drivers/scripts/stats/global_chem/jevs_global_chem_atmos_grid2obs_aeronet_stats.sh
  dev/drivers/scripts/stats/global_chem/jevs_global_chem_atmos_grid2obs_airnow_stats.sh
  dev/modulefiles/global_chem/global_chem_stats.sh
  ecf/defs/evs-nco.def
  ecf/scripts/stats/global_chem/jevs_global_chem_atmos_grid2obs_aeronet_stats_vhr_master.ecf
  ecf/scripts/stats/global_chem/jevs_global_chem_atmos_grid2obs_airnow_stats_vhr_master.ecf
  jobs/JEVS_GLOBAL_CHEM_STATS
  jobs/JEVS_GLOBAL_ENS_STATS
  parm/metplus_config/stats/global_chem/atmos_grid2obs/PointStat_fcstGEFSAero_obsAERONET.conf
  parm/metplus_config/stats/global_chem/atmos_grid2obs/PointStat_fcstGEFSAero_obsAIRNOW.conf
  parm/metplus_config/stats/global_chem/atmos_grid2obs/Statanalysis_fcstGEFSAero_obsAERONET.conf
  parm/metplus_config/stats/global_chem/atmos_grid2obs/Statanalysis_fcstGEFSAero_obsAIRNOW.conf
  scripts/stats/global_chem/exevs_global_chem_atmos_grid2obs_stats.sh
Labels: enhancement, cleanup

#749 Feature/sref add valid name to plot title
  dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.sh
  ecf/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_last90days_plots.ecf
  scripts/plots/mesoscale/exevs_mesoscale_sref_cape_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cloud_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_cnv_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_sref_td2m_plots.sh
  ush/mesoscale/ush_sref_plot_cnv_py/check_variables.py
  ush/mesoscale/ush_sref_plot_cnv_py/lead_average.py
  ush/mesoscale/ush_sref_plot_cnv_py/threshold_average.py
  ush/mesoscale/ush_sref_plot_precip_py/check_variables.py
  ush/mesoscale/ush_sref_plot_precip_py/lead_average.py
  ush/mesoscale/ush_sref_plot_precip_py/threshold_average.py
  ush/mesoscale/ush_sref_plot_py/check_variables.py
  ush/mesoscale/ush_sref_plot_py/lead_average.py
  ush/mesoscale/ush_sref_plot_py/threshold_average.py
Labels: enhancement

#747 global_ens: modify naefs prep job for MPMD processes
  dev/drivers/scripts/prep/global_ens/jevs_global_ens_headline_prep.sh
  ush/global_ens/evs_get_gens_atmos_data.sh
  ush/global_ens/evs_get_naefs_atmos_data.sh
Labels: NCO Bugzilla, cleanup

#752 Adding last31days to analyses plots
  dev/drivers/scripts/plots/analyses/jevs_analyses_grid2obs_plots_last31days.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/analyses/jevs_analyses_grid2obs_plots_last31days.ecf
Labels: cleanup

#750 Add validation data used to global-det plot title and add back monthly-mean dashed line to long-term plots
  dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_means_plots_last31days.sh
  dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_means_plots_last90days.sh
  dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_precip_plots_last31days.sh
  dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_ptype_plots_last90days.sh
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_means_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_precip_plots_last31days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_precip_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_pres_levs_plots_last31days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_pres_levs_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_last31days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_pres_levs_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_ptype_plots_last90days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_last31days.ecf
  ecf/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_last90days.ecf
  ush/global_det/global_det_atmos_copy_job_dir_output.py
  ush/global_det/global_det_atmos_plots.py
  ush/global_det/global_det_atmos_plots_headline.py
  ush/global_det/global_det_atmos_plots_long_term.py
  ush/global_det/global_det_atmos_plots_long_term_annual_mean.py
  ush/global_det/global_det_atmos_plots_long_term_lead_by_date.py
  ush/global_det/global_det_atmos_plots_long_term_time_series.py
  ush/global_det/global_det_atmos_plots_long_term_time_series_diff.py
  ush/global_det/global_det_atmos_plots_long_term_time_series_multifhr.py
  ush/global_det/global_det_atmos_plots_long_term_useful_forecast_days.py
  ush/global_det/global_det_atmos_plots_specs.py
Labels: enhancement

#753 Updated colors for hits/FAs to be colorblind-friendly
  ush/hurricane/false_al.py
  ush/hurricane/false_ep.py
  ush/hurricane/false_wp.py
  ush/hurricane/hits_al.py
  ush/hurricane/hits_ep.py
  ush/hurricane/hits_wp.py
  ush/hurricane/tcgen_space_al.py
  ush/hurricane/tcgen_space_ep.py
  ush/hurricane/tcgen_space_wp.py
Labels: enhancement

#754 Fix mesoscale grid2obs stats
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.sh
  ecf/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.ecf
  ush/mesoscale/mesoscale_create_output_dirs.py
Labels: bug

#755 feature/global_ens_wave_fix_part1
  dev/drivers/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.sh
  dev/modulefiles/global_ens/global_ens_prep.sh
  ecf/defs/evs-nco.def
  ecf/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.ecf
  parm/metplus_config/prep/global_ens/wave_grid2obs/PB2NC_wave.conf
  parm/metplus_config/stats/global_ens/wave_grid2obs/PointStat_fcstGEFS_obsGDAS_climoERA5_Wave_Multifield.conf
  scripts/plots/global_ens/exevs_global_ens_wave_grid2obs_plots.sh
  scripts/prep/global_ens/exevs_global_ens_wave_grid2obs_prep.sh
  scripts/stats/global_ens/exevs_global_ens_wave_grid2obs_stats.sh
  ush/global_ens/evs_wave_leadaverages.sh
  ush/global_ens/evs_wave_timeseries.sh
  ush/global_ens/global_ens_wave_plots_copy_plots.sh
  ush/global_ens/lead_average.py
  ush/global_ens/plot_util.py
  ush/global_ens/prune_stat_files.py
  ush/global_ens/settings.py
  ush/global_ens/time_series.py
  ush/global_ens/ush_gens_plot_py/prune_stat_files.py
Labels: NCO Bugzilla

#760 Bugfix/subseasonal initdate J-job edit
  jobs/JEVS_SUBSEASONAL_PREP
Labels: enhancement

#762 Fix issue with let command in rtma precip analysis stats job
  scripts/stats/analyses/exevs_analyses_rtma_precip_stats.sh
Labels: Known Issue

#759 JASON-3 match window fix for 00Z
  parm/metplus_config/stats/global_det/wave_grid2obs/PointStat_fcstGLOBAL_DET_obsJASON3_climoERA5_Wave_Multifield.conf
  scripts/stats/global_det/exevs_global_det_wave_grid2obs_stats.sh
Labels: enhancement

#764 HREF: adjust walltimes for some stats jobs
  dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh
  ecf/scripts/stats/cam/jevs_cam_href_grid2obs_stats.ecf
  ecf/scripts/stats/cam/jevs_cam_href_precip_stats.ecf
  ecf/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.ecf
Labels: cleanup

#761 Feature/add obs source
  ush/cam/cam_create_output_dirs.py
  ush/cam/lead_average.py
  ush/cam/performance_diagram.py
  ush/cam/prune_stat_files.py
  ush/cam/settings.py
  ush/cam/stat_by_level.py
  ush/cam/threshold_average.py
  ush/cam/time_series.py
  ush/cam/valid_hour_average.py
Labels: enhancement, Known Issue

#765 AQM hourly time series line type update
  dev/modulefiles/aqm/aqm_plots.sh
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_daily_plots_last90days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last31days.ecf
  ecf/scripts/plots/aqm/jevs_aqm_grid2obs_hourly_plots_last90days.ecf
  scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh
  ush/aqm/aqm_copy_job_dir_output.py
  ush/aqm/aqm_plots.py
  ush/aqm/aqm_plots_grid2obs_create_job_scripts.py
  ush/aqm/aqm_plots_performance_diagram.py
  ush/aqm/aqm_plots_specs.py
  ush/aqm/aqm_plots_time_series_fhr_mean.py
  ush/aqm/aqm_util.py
Labels: enhancement

#763 Bugfix/break up jobs
  dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_namnest_snowfall_stats.sh
  ecf/scripts/stats/cam/jevs_cam_hireswarw_precip_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hrrr_precip_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_namnest_snowfall_stats_vhr_master.ecf
  jobs/JEVS_CAM_STATS
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.hireswarw
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.hireswarwmem2
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.hireswfv3
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.hrrr
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.precip.namnest
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.hireswarw
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.hireswarwmem2
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.hireswfv3
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.hrrr
  parm/evs_config/cam/config.evs.prod.stats.cam.atmos.snowfall.namnest
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsMETAR.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsMETAR_VAR2.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB.conf
  parm/metplus_config/stats/cam/grid2obs/PointStat_fcstCAM_obsRAOB_VAR2.conf
  parm/metplus_config/stats/cam/precip/GridStat_fcstCAM_obsCCPA.conf
  parm/metplus_config/stats/cam/precip/GridStat_fcstCAM_obsMRMS.conf
  parm/metplus_config/stats/cam/snowfall/GridStat_fcstCAM_obsNOHRSC.conf
  scripts/stats/cam/exevs_hireswarw_grid2obs_stats.sh
  scripts/stats/cam/exevs_hireswarw_precip_stats.sh
  scripts/stats/cam/exevs_hireswarw_snowfall_stats.sh
  scripts/stats/cam/exevs_hireswarwmem2_grid2obs_stats.sh
  scripts/stats/cam/exevs_hireswarwmem2_precip_stats.sh
  scripts/stats/cam/exevs_hireswarwmem2_snowfall_stats.sh
  scripts/stats/cam/exevs_hireswfv3_grid2obs_stats.sh
  scripts/stats/cam/exevs_hireswfv3_precip_stats.sh
  scripts/stats/cam/exevs_hireswfv3_snowfall_stats.sh
  scripts/stats/cam/exevs_href_precip_stats.sh
  scripts/stats/cam/exevs_hrrr_grid2obs_stats.sh
  scripts/stats/cam/exevs_hrrr_precip_stats.sh
  scripts/stats/cam/exevs_hrrr_snowfall_stats.sh
  scripts/stats/cam/exevs_namnest_grid2obs_stats.sh
  scripts/stats/cam/exevs_namnest_precip_stats.sh
  scripts/stats/cam/exevs_namnest_snowfall_stats.sh
  ush/cam/cam_check_input_data.py
  ush/cam/cam_stats_grid2obs_create_job_script.py
  ush/cam/cam_stats_precip_create_job_script.py
  ush/cam/cam_stats_snowfall_create_job_script.py
  ush/cam/cam_util.py
  ush/cam/evs_href_snowfall.sh
Labels: bug, enhancement

#769 Adjusting mesoscale plot restart
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.grid2obs
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.headline
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.precip
  parm/evs_config/mesoscale/config.evs.prod.plots.mesoscale.atmos.snowfall
  scripts/plots/mesoscale/exevs_mesoscale_grid2obs_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_precip_plots.sh
  scripts/plots/mesoscale/exevs_mesoscale_snowfall_plots.sh
  ush/mesoscale/lead_average.py
  ush/mesoscale/mesoscale_create_child_workdirs.py
  ush/mesoscale/mesoscale_create_output_dirs.py
  ush/mesoscale/mesoscale_plots_grid2obs_create_job_script.py
  ush/mesoscale/mesoscale_plots_grid2obs_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_grid2obs_create_poe_job_scripts.py
  ush/mesoscale/mesoscale_plots_headline_create_job_script.py
  ush/mesoscale/mesoscale_plots_precip_create_job_script.py
  ush/mesoscale/mesoscale_plots_precip_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_precip_create_poe_job_scripts.py
  ush/mesoscale/mesoscale_plots_precip_spatial_map.py
  ush/mesoscale/mesoscale_plots_snowfall_create_job_script.py
  ush/mesoscale/mesoscale_plots_snowfall_create_job_scripts.py
  ush/mesoscale/mesoscale_plots_snowfall_create_poe_job_scripts.py
  ush/mesoscale/mesoscale_production_restart.py
  ush/mesoscale/performance_diagram.py
  ush/mesoscale/spatial_map.py
  ush/mesoscale/stat_by_level.py
  ush/mesoscale/threshold_average.py
  ush/mesoscale/time_series.py
  ush/mesoscale/valid_hour_average.py
Labels: Known Issue

#773 Bugfix/increase memory
  dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
  dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
  ecf/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_hrrr_precip_stats_vhr_master.ecf
  ecf/scripts/stats/cam/jevs_cam_namnest_precip_stats_vhr_master.ecf
Labels: cleanup
