Repository NOAA-EMC/EVS, pull requests merged in 2025-08, with the labels that each got.

#789 Updated RTOFS version number.
  dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh
  ecf/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.ecf
  versions/run.ver
Labels: update

#793 NAM/RAP - fix restart for grid2obs stats
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh
  dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.sh
  ecf/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.ecf
  ecf/scripts/stats/mesoscale/jevs_mesoscale_rap_grid2obs_stats.ecf
  ush/mesoscale/mesoscale_stats_grid2obs_create_job_script.py
Labels: bug

#794 global_ens: change sea ice concentration threshold from 10% to 15%
  dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_sea_ice_stats.sh
  parm/metplus_config/stats/global_ens/atmos_grid2grid/GridStat_fcstGEFS_obsOSI_SAF_mean.conf
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_sea_ice_plots.sh
  ush/global_ens/ush_gens_plot_py/settings.py
Labels: Known Issue

#798 global_ens: use split_by_subset to trim prepbufr files
  ecf/scripts/prep/global_ens/jevs_global_ens_atmos_prep.ecf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/Pb2nc_obsGFS_Prepbufr.conf
  parm/metplus_config/stats/global_ens/atmos_grid2obs/Pb2nc_obsGFS_Prepbufr_Profile.conf
  ush/global_ens/evs_get_gens_atmos_data.sh
Labels: Known Issue

#800 Use prod versions of EVS v2.0 VE, MET-12.0.1, METplus-6.0.0
  dev/modulefiles/analyses/analyses_plots.sh
  dev/modulefiles/analyses/analyses_stats.sh
  dev/modulefiles/aqm/aqm_plots.sh
  dev/modulefiles/aqm/aqm_prep.sh
  dev/modulefiles/aqm/aqm_stats.sh
  dev/modulefiles/cam/cam_plots.sh
  dev/modulefiles/cam/cam_prep.sh
  dev/modulefiles/cam/cam_stats.sh
  dev/modulefiles/global_chem/global_chem_plots.sh
  dev/modulefiles/global_chem/global_chem_prep.sh
  dev/modulefiles/global_chem/global_chem_stats.sh
  dev/modulefiles/global_det/global_det_plots.sh
  dev/modulefiles/global_det/global_det_prep.sh
  dev/modulefiles/global_det/global_det_stats.sh
  dev/modulefiles/global_ens/global_ens_plots.sh
  dev/modulefiles/global_ens/global_ens_prep.sh
  dev/modulefiles/global_ens/global_ens_stats.sh
  dev/modulefiles/glwu/glwu_plots.sh
  dev/modulefiles/glwu/glwu_prep.sh
  dev/modulefiles/glwu/glwu_stats.sh
  dev/modulefiles/hurricane/hurricane_plots.sh
  dev/modulefiles/hurricane/hurricane_stats.sh
  dev/modulefiles/mesoscale/mesoscale_plots.sh
  dev/modulefiles/mesoscale/mesoscale_prep.sh
  dev/modulefiles/mesoscale/mesoscale_stats.sh
  dev/modulefiles/narre/narre_plots.sh
  dev/modulefiles/narre/narre_stats.sh
  dev/modulefiles/nfcens/nfcens_plots.sh
  dev/modulefiles/nfcens/nfcens_prep.sh
  dev/modulefiles/nfcens/nfcens_stats.sh
  dev/modulefiles/nwps/nwps_plots.sh
  dev/modulefiles/nwps/nwps_prep.sh
  dev/modulefiles/nwps/nwps_stats.sh
  dev/modulefiles/rtofs/rtofs_plots.sh
  dev/modulefiles/rtofs/rtofs_prep.sh
  dev/modulefiles/rtofs/rtofs_stats.sh
  dev/modulefiles/seasonal/seasonal_plots.sh
  dev/modulefiles/seasonal/seasonal_prep.sh
  dev/modulefiles/seasonal/seasonal_stats.sh
  dev/modulefiles/subseasonal/subseasonal_plots.sh
  dev/modulefiles/subseasonal/subseasonal_prep.sh
  dev/modulefiles/subseasonal/subseasonal_stats.sh
  dev/modulefiles/wafs/wafs_plots.sh
  dev/modulefiles/wafs/wafs_stats.sh
Labels: enhancement

#804 Updating analyses prep and rtofs stats modulefiles
  dev/modulefiles/analyses/analyses_prep.sh
  dev/modulefiles/rtofs/rtofs_stats.sh
Labels: update

#803 global_ens: adjust atmos grid2grid and precip plots
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2grid_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2grid_last90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_precip_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_precip_last90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2grid_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2grid_last90days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_last31days_plots.sh
  dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_last90days_plots.sh
  ecf/defs/evs-nco.def
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2grid_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2grid_last90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_precip_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_precip_last90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2grid_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_grid2grid_last90days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_last31days_plots.ecf
  ecf/scripts/plots/global_ens/jevs_global_ens_atmos_naefs_precip_last90days_plots.ecf
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_grid2grid_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_gefs_precip_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_naefs_grid2grid_plots.sh
  scripts/plots/global_ens/exevs_global_ens_atmos_naefs_precip_plots.sh
Labels: cleanup, Known Issue

#774 Add WAFS wind direction verification to EVSv2.0
  dev/drivers/scripts/plots/wafs/jevs_wafs_atmos_plots.sh
  dev/drivers/scripts/stats/wafs/jevs_wafs_atmos_stats.sh
  ecf/scripts/stats/wafs/jevs_wafs_atmos_stats.ecf
  jobs/JEVS_WAFS_PLOTS
  jobs/JEVS_WAFS_STATS
  parm/evs_config/wafs/config.evs.plots.wafs.atmos
  parm/evs_config/wafs/config.evs.wafs.standalone
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGCIPicesev.conf
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGFSuvt.conf
  parm/metplus_config/stats/wafs/atmos/GridStat_fcstWAFS_obsGFSwdir.conf
  parm/metplus_config/stats/wafs/atmos/StatAnalysis_fcstWAFS_obsGCIPicesev_GatherbyDay.conf
  parm/metplus_config/stats/wafs/atmos/StatAnalysis_fcstWAFS_obsGFSuvt_GatherbyDay.conf
  parm/metplus_config/stats/wafs/atmos/StatAnalysis_fcstWAFS_obsGFSwdir_GatherbyDay.conf
  parm/metplus_config/stats/wafs/atmos/grib2_wafs.txt
  scripts/plots/wafs/exevs_wafs_atmos_plots.sh
  scripts/stats/wafs/exevs_wafs_atmos_stats.sh
  ush/wafs/evs_wafs_atmos_plot_check_variables.py
  ush/wafs/evs_wafs_atmos_plot_prune_stat_files.py
  ush/wafs/evs_wafs_atmos_plot_roc_curve.py
  ush/wafs/evs_wafs_atmos_plot_settings.py
  ush/wafs/evs_wafs_atmos_plot_time_series.py
  ush/wafs/evs_wafs_atmos_plot_util.py
  ush/wafs/evs_wafs_atmos_plots.sh
  ush/wafs/evs_wafs_atmos_stats.sh
  ush/wafs/evs_wafs_atmos_stats_preparedata.sh
Labels: enhancement
